### ISSUE TITLE
Check for duplicate species in a phase

### ISSUE THREAD

**Issue by boulderdaze** [NCAR/MechanismConfiguration#114]
Check for Duplicate Species in a Phase

Parsing should fail if a phase contains duplicate species. Each species in a phase must be unique.

Example:

```YAML
phases:
  - name: gas
    species: [O2, N2, O2]  # duplicate O2
```

`Error: Duplicate species 'O2' found in phase 'gas'`
